# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classifier_pb2 as classifier__pb2


class AksaraJawaClassifierStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/classifier.AksaraJawaClassifier/Classify',
                request_serializer=classifier__pb2.Parameters.SerializeToString,
                response_deserializer=classifier__pb2.Prediction.FromString,
                )


class AksaraJawaClassifierServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AksaraJawaClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=classifier__pb2.Parameters.FromString,
                    response_serializer=classifier__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classifier.AksaraJawaClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AksaraJawaClassifier(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/classifier.AksaraJawaClassifier/Classify',
            classifier__pb2.Parameters.SerializeToString,
            classifier__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
