# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classifier.proto',
  package='classifier',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x63lassifier.proto\x12\nclassifier\"?\n\nPrediction\x12\x0f\n\x07\x63lassID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\x1a\n\nParameters\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32T\n\x14\x41ksaraJawaClassifier\x12<\n\x08\x43lassify\x12\x16.classifier.Parameters\x1a\x16.classifier.Prediction\"\x00\x62\x06proto3'
)




_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='classifier.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classID', full_name='classifier.Prediction.classID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='classifier.Prediction.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='classifier.Prediction.confidence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=95,
)


_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='classifier.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='classifier.Parameters.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier.Prediction)
  })
_sym_db.RegisterMessage(Prediction)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERS,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier.Parameters)
  })
_sym_db.RegisterMessage(Parameters)



_AKSARAJAWACLASSIFIER = _descriptor.ServiceDescriptor(
  name='AksaraJawaClassifier',
  full_name='classifier.AksaraJawaClassifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='classifier.AksaraJawaClassifier.Classify',
    index=0,
    containing_service=None,
    input_type=_PARAMETERS,
    output_type=_PREDICTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AKSARAJAWACLASSIFIER)

DESCRIPTOR.services_by_name['AksaraJawaClassifier'] = _AKSARAJAWACLASSIFIER

# @@protoc_insertion_point(module_scope)
